version: 2
updates:
- package-ecosystem: pnpm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: pnpm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: pnpm
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 20