name: "🚀 Feature request"
description: Suggest a feature that will improve NCU+
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition to NCU+, including the possible use cases and alternatives you have considered.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
        - label: Could this feature be implemented as a plugin?
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Check existing [issues](https://github.com/NCU-Plus/ncuplus/issues).
          required: true
