name: CD

on:
  release:
    types: [released, edited]

jobs:
  release-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ppodds/relno-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  get-version:
    uses: ppodds/workflows/.github/workflows/get-version-from-tag.yml@master
    with:
      tag: ${{ github.event.release.tag_name }}
  docker:
    needs: get-version
    runs-on: ubuntu-latest
    name: "Build Docker image and push to Docker Hub"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build frontend and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ppodds/ncuplus-frontend:latest,ppodds/ncuplus-frontend:${{ needs.get-version.outputs.version }}
        file: Dockerfile.frontend
    - name: Build backend and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ppodds/ncuplus-backend:latest,ppodds/ncuplus-backend:${{ needs.get-version.outputs.version }}
        file: Dockerfile.backend
  trigger-deploy:
    needs:
      - docker
      - get-version
    uses: ppodds/workflows/.github/workflows/update-helm-chart.yml@master
    with:
      repo: ppodds/ncuplus-helm
      app_version: ${{ needs.get-version.outputs.version }}
    secrets:
      TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
