name: Run E2E Tests

on:
  workflow_call:
jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.17.0-chrome106
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .output
      - name: Clean tsconfig
        run: echo '{}' > tsconfig.json
      - name: Disable husky install
        run: npm pkg delete scripts.prepare
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          start: node .output/server/index.mjs
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
