name: Run Tests

on:
  pull_request:
jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yml
  e2e-tests:
    uses: ./.github/workflows/e2e-test.yml
    secrets:
      cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
      oauth-client-id: ${{ secrets.OAUTH_CLIENT_ID }}
      oauth-client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}